name: help-command-app
on:
  repository_dispatch:
    types: [help-command-app]
jobs:
  help:
    runs-on: ubuntu-latest
    steps:
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            > Le slash command napp vous permet d’interagir ou d’exécuter des actions sur nos répository github. 
            > Commande | Déscription
            > --- | ---
            > /publish-preview | build et publie une version de prévisualisation de l'application
            > /updagrade-to-beta  | Fait un PR de la branche release/* vers la branche staging
            > /updagrade-to-prod  | Fait un PR de la branche staging vers la branche production
            > /start-pr [\<branch=\>]<name_branch> | Fait un PR à la branche spécifier.(par défaut: dev)
            > /help | Obtenir de l'aide sur slash command 
          reaction-type: eyes
