name: start-pull-request
on:
  repository_dispatch:
    types: [start-pr-command,upgrade-to-beta-command,start-pr-command,updgrade-to-prod]
jobs:
  start-generic-pull-request:
    uses: bilwifi/gh-action-test/.github/workflows/generic-start-pull-request-from-issue.yml@main
    secrets: inherit
